#!/bin/sh
#
# Hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.

echo "Executing tests before commit"

./gradlew clean test

# check command result for success
result=$?
if [ "$result" -ne 0 ]; then
 echo "Tests failed. Commit prevented."
fi
exit $result